# Generated by Django 2.0.3 on 2018-03-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.TextField()),
                ('isDone', models.BooleanField(default=False)),
                ('doneAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
